### ISSUE TITLE
Sorry.. the Pirateweather forecast is not available

### ISSUE THREAD

**Issue by Valley8140** [ktrue/PW-forecast#1]
Hi, I'm running Pw within a WordPress site. Pw files have been uploaded and edited using a WordPress plugin "Advanced file manager" which is a bit like a Cpanel utility. I've run into 2 issues.

I've changed the list of towns but it doesn't show on the website; it still shows the default list
the above message ("Sorry.. the Pirateweather forecast is not available.") has now been showing. Is this a cache related issue (as maybe the first issue is?)

**Comment by ktrue** [comment]
What is the URL to the page showing the issue.. I'll take a look.

WordPress may be doing some odd stuff behind the scenes.  Do you have a plugin to run native PHP apps installed on your WordPress?

**Comment by Valley8140** [comment]
you can find the error on https://7002650.net/?page_id=1889 (password 265). There is a plugin running for PHP shortcodes [http://xyzscripts.com/wordpress-plugins/insert-php-code-snippet/](url), the forecast (https://7002650.net/weather/forecastgalore.php) itself is delivered to the above page in an iframe.
It was running initially if not for the incorrect list of towns, in stand alone and in template (currently only running stand alone). I have regenerated the API but that didn't work either.

**Comment by ktrue** [comment]
IF you look at view-source:https://7002650.net/weather/forecastgalore.php it shows:
```
<!-- loading from https://api.pirateweather.net/forecast/{redacted}/-35.004144658621755, 146.81763343849755?exclude=minutely&extend=hourly&units=si. -->
<!-- curl fetching 'https://api.pirateweather.net/forecast/{redacted}/-35.004144658621755, 146.81763343849755?exclude=minutely&extend=hourly&units=si' -->
<!-- HTTP stats:  RC=0 dest= port=0 (from sce=)
      Times: dns=0.000 conn=0.000 pxfer=0.000 total=0.000 secs -->
<!-- headers:

 -->
<!-- RC=, bytes=0 -->
```
Since the curl return is almost instant, I suspect something is blocking curl from access to the internet.   Check any application firewall on your site for permission to use curl/internet access.

**Comment by Valley8140** [comment]
Hosting is done by third party who confirmed curl is available. In the meantime, it seemed that in this case json.txt was not being created?
`bad return from https://api.pirateweather.net/etcetc?exclude=minutely&extend=hourly&units=si
false
 -->
cache ./PW-forecast-json-0-si.txt missing or contains invalid contents -->
`
I now have deleted the whole directory and started all over again, this seems to work so far.
