### ISSUE TITLE
LAnguage 

### ISSUE THREAD

**Issue by RV88470** [ktrue/PW-forecast#2]
Good morning,
In this script the default display language is English!
How to have the default language in French?
Sincerely
Hervé

**Comment by ktrue** [comment]
In the PW-forecast.php script set
```
$charsetOutput = 'UTF-8';            // for standalone use if desired
$lang = 'fr';	// default language
```

**Comment by RV88470** [comment]
Thank you very much for this response.

**Comment by ktrue** [comment]
You are welcome!  I'm glad you are enjoying the script.
